### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by lesajo** [thobach/MMM-WunderGround24Hours#1]
Hello, i have installed the asset and now.. ? i dont get the information for 4.. 
have do all what u write down in your  readme..

plz help.

thx u

**Comment by thobach** [comment]
Hi lesajo,
There is no step 4 in https://github.com/thobach/MMM-WunderGround24Hours/blob/master/README.MD. What problem are you facing?
Thanks,
Thomas

**Comment by lesajo** [comment]
Hi Thomas.  ich hoffe es ist nicht schlimm wenn ich auf deutsch schreibe..

was die 4 da zu suchen hat, weiß ich grad nicht :D 

ich hab das so gemacht wie du das beschrieben hast, aber.. ich bekomme die informationen nicht, die dort stehen sollten.. Temperatiur, Graph und so weiter.

der inhlat bleibt einfach leer..

**Comment by thobach** [comment]
Wenn du die Seite des Magic Mirror auf einem Desktop Browser aufrufst, und
in die Entwicklerkonsole des Browsers gehst, welche JavaScript
Fehlermeldung siehst du?

**Comment by lesajo** [comment]
Ich kann den nicht aufrufen.. wenn ich node serveronly mache, startet der auf dem PI aber auf meinem desktop pc hab ich nur eine weiße seite.

**Comment by lesajo** [comment]
irgendeine idee ? würde gerne schöneres wetter anzeigen lassen.

ich könnte dir auch mal teamviewer daten geben. :)

**Comment by thobach** [comment]
Hast du schon versucht deine lokale IP Adresse im Magic Mirror freizugeben? Es gibt dazu eine Anleitung auf https://forum.magicmirror.builders/topic/1326/ipwhitelist-howto. Ansonsten schlage ich vor allgemeine Fragen zum Debugging auf https://forum.magicmirror.builders/ zu stellen. Wenn du eine Fehlermeldung bekommst, kann ich dir gern hier auf GitHub weiterhelfen.
Thomas

**Comment by lesajo** [comment]
das darfst du echt keinem sagen ^^
ich schäme mich ja sc hon. :D naja ich lese immer nur die haelfte.. "pws:asdsadsa" pws vergessen
