### ISSUE TITLE
Trouble with temperature

### ISSUE THREAD

**Issue by Softyathome** [thobach/MMM-WunderGround24Hours#2]
Hi,

i allways get 19C on my Mirror. Every day … :-(
Where can i adjust it?
Any ideas?

Regards

**Comment by thobach** [comment]
Hi Softyathome,
Which station ID are you using? Have you tried with different stations or restarting your mirror?
I recently noticed that a lot of my local stations were removed, maybe yours is also affected.
Thomas

**Comment by Softyathome** [comment]
Hallo Thomas,

wir können auch gerne deutsch schreiben :-).
Mit StationID ist die appid gemeint?
Kann ich die hier angeben?

Und "Ja", leider hängt sich mein Spiegel immer wieder nach 1-2 Tagen auf -
habe dann nur noch einen schwarzen Bildschirm.
Erst nach einem Neustart ist mein Spiegel wieder da .. :-(
Webzugriff ist weiterhin möglich.
Ich denke, dass das im Zusammenhang mit meinem Ultraschallsensor und dem
Script liegt, doch dazu ggf. später.
Gruß
Jens


Am Do., 21. Juni 2018 um 11:26 Uhr schrieb Thomas Bachmann <
notifications@github.com>:

**Comment by Softyathome** [comment]
Kann das der Grund sein …
See here:
https://www.wunderground.com/weather/api/
They wrote:
“To improve our services and enhance our relationship with our users, we
will no longer provide free weather API keys as part of our program.”

Am Do., 21. Juni 2018 um 14:37 Uhr schrieb Jens Wachholz <
jens.wachholz@gmail.com>:

**Comment by Softyathome** [comment]
Ein anderer User hatte die gleichen Probleme …
Meine "Station" gibt es nicht mehr. Mit einer neuen klappt das wieder
"wunderbar" ;-)
Also: erledigt
Danke & Gruß

Am Do., 21. Juni 2018 um 19:05 Uhr schrieb Jens Wachholz <
jens.wachholz@gmail.com>:

**Comment by thobach** [comment]
Ist das Problem mit dem Wechsel zur Dark Sky API verschwunden?
