### ISSUE TITLE
Sometimes the temperature and forecasts are freezing

### ISSUE THREAD

**Issue by McNose** [thobach/MMM-WunderGround24Hours#3]
Hi Thomas,

first of all: Thanks for that great module.
As a motobiker I love it:-)

Unfortunately sometimes the whole module is freezing. Time stand still and the temperature is not changing anymore. Same the forecast dates.
The mirror is still working. It is just the module. If I restart the mirror everthing is fine again.

Do you have an idea what the problem might be?

However I wonder if it is possible to leave wunderground and integrate the data of my own netatmo modules.
Do you have any experiance at this?

Thanks a lot.

Greetings.
Mr.Coffee

**Comment by thobach** [comment]
I think the freezing is resolved with the move to the Dark Sky API.

I don't plan to integrate with own netatmo modules, sorry.
