### ISSUE TITLE
failed to load url. No 'Access-Control-Allow-Origin' header is present on the requested ressource

### ISSUE THREAD

**Issue by Com-Lum** [thobach/MMM-WunderGround24Hours#5]
Hello, 
I just tried your module but within the MM it is not working. The 'dev'-log shows the error written in the header.
When i copy the url from the module and test it with a normal browser i get the correct results... Do you have seen this error during creation of the module, too?

Best regards

**Comment by thobach** [comment]
Hi Com-Lum,
Did you follow step 3 from https://github.com/thobach/MMM-DarkSky24Hours to disable CORS?
Thanks,
Thomas

**Comment by Com-Lum** [comment]
ok, that i thought is only for "browser" version. I should have read the text completely^^.
It is working except the picture of the current weather?
This is not loaded but i get an error for a module "moment"
i get this only when the "electron" part is added.

____
Uncaught Error: Cannot find module 'moment'
    at Module._resolveFilename (module.js:543)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35)
    at Function.Module._load (module.js:473)
    at Module.require (module.js:586)
    at require (internal/module.js:11)
    at moment-timezone-with-data.js:14
    at moment-timezone-with-data.js:18
_____

**Comment by Com-Lum** [comment]
ok, I did not see the update from yesterday. everything working!
Thanks!
